Algoritmo "9 - EXER. 1"

Var

   I, F, CONT: Inteiro
inicio
   Escreval("CONTAGEM INTELIGENTE")
   Escreval("--------------------")

   Escreva ("Inicio: ")
   Leia(I)

   Escreva ("Fim: ")
   Leia(F)

   Escreval("--------------------")
   Escreval("  C O N T A N D O   ")
   Escreval("--------------------
   
   se (f > i) entao

   enquanto (contador <= ) faca
      escreval(contador)
      contador <- contador - 1)
   fimenquanto



Fimalgoritmo