Algoritmo "90 - exer. alg."
// 
//  
// 90) Desenvolva um algoritmo que leia dois valores pelo teclado e passe esses valores
//para um procedimento Somador() que vai calcular e mostrar a soma entre eles.
Var

n1, n2: inteiro

procedimento somador (a, b: inteiro)
inicio
escreval("a soma é ",a + B)

escreva(a)

fimprocedimento

Inicio
escreval("DIGITE UM VALOR: ")
leia(n1)
escreval("DIGITE UM VALOR: ")
leia(n2)
somador (n1, n2)

escreva(a)


Fimalgoritmo